## **Data Accessing**

Types of Unclean Data<br>
1) Dirty Data (Data with Qulaity issues) Dirty data ,also known as low quality data , 
- Duplicated Values 
- Missing Data 
- Corrupt Data
- inaccurate data <br>
2) messy Data(data with tidiness issues) Messy data, Data with structural issue  Tidy Data have following properties
- Each Variable forms a column
- Each observation forms a row 
- Each obseravation unit forms a table

In [7]:
import pandas as pd
import numpy as np

In [8]:
patients = pd.read_csv(r"C:\Users\LENOVO\Downloads\patients.csv")
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [9]:
treatments = pd.read_csv(r"C:\Users\LENOVO\Downloads\treatments.csv")
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [10]:
treatment_cut = pd.read_csv(r"C:\Users\LENOVO\Downloads\treatments_cut.csv")
treatment_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [11]:
adverse = pd.read_csv(r"C:\Users\LENOVO\Downloads\adverse_reactions.csv")
adverse.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

Write a summary of a data<br>
Write column Discription

## **Types of asscess**
- manual
- programatic

In [ ]:
# export data for manual accessing
with pd.ExcelWriter('clinical_trails.xlsx') as writer:
    patients.to_excel(writer,sheet_name='patients')
    treatments.to_excel(writer,sheet_name='treatments')
    treatment_cut.to_excel(writer,sheet_name= 'treatment_cut')
    adverse.to_excel(writer,sheet_name='adverse_reactions')

# **Issue With DataSet**
1. Dirty Data<br>
Table `patients:` <br>
- patient id 9 has miss spelled  name 'dsvid' insted of david(`accuracy issue`)
- state columns sometimes contain full name and sometimes abbrivations(`consistency issue`)
- 12 patients data is missing in  5 columns `address city state zip_code country contact`  (`compleateness issue`)
- assigned_sex is in string(change in category) zip code in float(change in int), birthdate is in object(change in date-time)(`validity issue`)
- 5 duplicated values in columns `given_name` and `surname`(by name of john doe)(`accuracy issue`)
- there is a patient with 48 pond (~21 kg ) invalid entry(`accuracy`)
- one patient has hight = 27 feet(`accuarcy`)
- zip code column has 5 digit sometimes 5 <br>
Table `treatment` & `treatment_cut`<br>
- given_name in both datasets are in diffrent cases , in patients name is in title case , and in treatment it in lower case(`consistency`)
- remove u from auralin & novodra(`validity`)
- '-' is replace with nan value for both auralin & novodra(`validity`)
- missing values in 'hba1c_change' columns(`compleation`)
- 1 duplicated value in treatments at index 136(drop that row)(`accuracy`)
- in change their is a wronge entry in hba1c_change ( 9 insted of 4)(`validity`)
Table `adverse` <br>
- name as in given name and sir_name column is lower case(`consistency`)
2. Messy Data<br>
Table `patients`
- in contact column both phone no and email.<br>
Table `treatment` & `treatment_cut`
- in auralin column both data should have in different columns like auralin_start , auralin_end
- simliarly for novodra we need splitting in both columns auralin & novodra<br>
- Merge both tables
Table `adverse`
-This table should not exist independently

# **Progamatic accessment**
- head tail
- sample
- info
- duplicated
- describe

In [12]:
treatments.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    str
 1   surname       280 non-null    str
 2   auralin       280 non-null    str
 3   novodra       280 non-null    str
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), str(4)
memory usage: 21.8 KB

In [13]:
patients.sample(5)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
301,302,female,Onyekachukwu,Obinna,2970 Forest Avenue,New York,NY,10004.0,United States,OnyekachukwuObinna@teleworm.us646-982-6609,1/24/1997,154.7,65,25.7
38,39,female,Genet,Fesahaye,4649 Joanne Lane,Westborough,MA,1581.0,United States,GenetFesahaye@armyspy.com1 978 460 9060,1/11/1954,111.8,67,17.5
147,148,male,Kristian,Vukelić,4411 Libby Street,West Los Angeles,California,90025.0,United States,310-268-6864KristianVukelic@teleworm.us,11/30/1958,191.4,66,30.9
169,170,male,Markus,Solberg,4148 Callison Lane,Bensalem,DE,19020.0,United States,302-474-8075MarkusSolberg@fleckens.hu,11/21/1953,140.6,70,20.2
13,14,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,AnenechiChidi@armyspy.com+1 (205) 417-8095,3/7/1961,228.4,67,35.8

In [14]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    str
 2   given_name    503 non-null    str
 3   surname       503 non-null    str
 4   address       491 non-null    str
 5   city          491 non-null    str
 6   state         491 non-null    str
 7   zip_code      491 non-null    float64
 8   country       491 non-null    str
 9   contact       491 non-null    str
 10  birthdate     503 non-null    str
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), str(9)
memory usage: 107.9 KB

In [15]:
patients.isnull().sum()

patient_id       0
assigned_sex     0
given_name       0
surname          0
address         12
city            12
state           12
zip_code        12
country         12
contact         12
birthdate        0
weight           0
height           0
bmi              0
dtype: int64

In [16]:
treatments.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    str
 1   surname       280 non-null    str
 2   auralin       280 non-null    str
 3   novodra       280 non-null    str
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), str(4)
memory usage: 21.8 KB

In [17]:
treatment_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     str
 1   surname       70 non-null     str
 2   auralin       70 non-null     str
 3   novodra       70 non-null     str
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), str(4)
memory usage: 5.6 KB

In [18]:
adverse.info()

<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     str
 1   surname           34 non-null     str
 2   adverse_reaction  34 non-null     str
dtypes: str(3)
memory usage: 1.8 KB

In [19]:
patients.duplicated().sum() # no duplicates

np.int64(0)

In [20]:
patients.duplicated(subset=['given_name','surname']).sum()

np.int64(5)

In [21]:
patients[patients.duplicated(subset=['given_name','surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [22]:
treatments.duplicated().sum() # having 1 dulicated value
treatments[treatments.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [23]:
treatment_cut.duplicated().sum() # no dulicates

np.int64(0)

In [24]:
treatments[treatments.duplicated(subset=['given_name','surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [25]:
adverse.duplicated().sum() # no duplicated values

np.int64(0)

In [26]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [27]:
patients[(patients['weight'] == 48.800000	)]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [28]:
patients[(patients['height'] == 27.000000)]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

# Note - Accessing data is an iterative Process

## **Data Quality Dimensions**
- compleatness ---> is data missing?
- validity ---> is data invalid --> negative height --> duplicated_patient_id
- Accuracy --> data is valid but not accurate ---> weight is 1 kg
- consistency ----> both valid and accurate but written differntly ---> new york ans NY

compleatness <---validity<---accuracy<---consistency

# **Data Cleaning Order**
- Quality --> compleateness
- Tidiness
- Quality --> validity
- Quality ----> accuracy
- Quality ---> consistency

# Steps involved in Data cleaning
- Define
- code 
- text
- - Always make sure to make a copy of our pandas df before start cleaning process

## **Difine**

In [29]:
# both dataset tratments and treatment_cut column(hb1ac_change is difference of hba1c_start and hba1c_end)

In [30]:
treatments['hba1c_change'] =  treatments['hba1c_start'] - treatments['hba1c_end']

In [31]:
treatments

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,0.32
277,mathea,lillebø,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samúel,guðbrandsson,53u - 56u,-,8.00,7.64,0.36

In [32]:
treatments.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    str
 1   surname       280 non-null    str
 2   auralin       280 non-null    str
 3   novodra       280 non-null    str
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), str(4)
memory usage: 21.8 KB

In [33]:
treatment_cut['hba1c_change'] =  treatment_cut['hba1c_start'] - treatment_cut['hba1c_end']

In [34]:
treatment_cut.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     str
 1   surname       70 non-null     str
 2   auralin       70 non-null     str
 3   novodra       70 non-null     str
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  70 non-null     float64
dtypes: float64(3), str(4)
memory usage: 5.6 KB

In [35]:
# in patients column contact has

In [36]:
treatment_df = pd.concat([treatments,treatment_cut],ignore_index=True)

In [37]:
treatment_df = treatment_df.melt(id_vars=['given_name','surname','hba1c_start','hba1c_end','hba1c_change'],var_name='Type',value_name='dose_range')

In [38]:
treatment_df = treatment_df[treatment_df['dose_range'] != '-']

In [39]:
treatment_df['dose_range'] = treatment_df['dose_range'].str.replace('u','')

In [40]:
treatment_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,Type,dose_range
0,veronika,jindrová,7.63,7.20,0.43,auralin,41 - 48
3,skye,gormanston,7.97,7.62,0.35,auralin,33 - 36
6,sophia,haugen,7.65,7.27,0.38,auralin,37 - 42
7,eddie,archer,7.89,7.55,0.34,auralin,31 - 38
9,asia,woźniak,7.76,7.37,0.39,auralin,30 - 36
...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55 - 51
690,maret,sultygov,7.67,7.30,0.37,novodra,26 - 23
694,lixue,hsueh,9.21,8.80,0.41,novodra,22 - 23
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28 - 26
698,berta,napolitani,7.68,7.21,0.47,novodra,42 - 44

In [41]:
treatment_df['dose_start'] = treatment_df['dose_range'].str.split(' ').str.get(0)

In [42]:
treatment_df['dose_end'] = treatment_df['dose_range'].str.split(' ').str.get(2)

In [43]:
treatment_df  =treatment_df.drop(columns='dose_range')

In [44]:
treatment_df[['dose_start','dose_end']] = treatment_df[['dose_start','dose_end']].astype('int16')

In [45]:
treatment_df.reset_index(drop=True)

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,Type,dose_start,dose_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42
3,eddie,archer,7.89,7.55,0.34,auralin,31,38
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36
...,...,...,...,...,...,...,...,...
345,christopher,woodward,7.51,7.06,0.45,novodra,55,51
346,maret,sultygov,7.67,7.30,0.37,novodra,26,23
347,lixue,hsueh,9.21,8.80,0.41,novodra,22,23
348,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26
349,berta,napolitani,7.68,7.21,0.47,novodra,42,44

In [46]:
adverse.head(1)

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort

In [47]:
treatment_df = treatment_df.merge(adverse,on=['given_name','surname'] ,how='left')

In [48]:
treatment_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,Type,dose_start,dose_end,adverse_reaction
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort