## **Binning/Discretization**

In [108]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [109]:
from sklearn.preprocessing import KBinsDiscretizer

In [110]:
titanic = pd.read_csv(r"C:\Users\LENOVO\Downloads\titanic.csv",usecols=['Age','Survived','Fare'])

In [111]:
titanic.sample(5)

     Survived   Age     Fare
179         0  36.0   0.0000
361         0  29.0  27.7208
824         0   2.0  39.6875
506         1  33.0  26.0000
781         1  17.0  57.0000

In [112]:
titanic['Age'] =  titanic['Age'].fillna(titanic['Age'].mean())

In [113]:
x = titanic.iloc[:,[1,-1]]
y = titanic.iloc[:,0]

In [114]:
x_train , x_test , y_train , y_test = train_test_split(titanic.iloc[:,[1,-1]],titanic.iloc[:,0],test_size=0.2,random_state=42)

In [115]:
x_test.shape,x_train.shape

((179, 2), (712, 2))

In [116]:
y_train.shape,y_test.shape

((712,), (179,))

In [117]:
dt = DecisionTreeClassifier()

In [118]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [119]:
y_pred = dt.predict(x_test)

In [120]:
accuracy_score(y_test,y_pred)

0.664804469273743

In [121]:
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,cv= 10, scoring='accuracy'))

np.float64(0.6621847690387016)

In [122]:
kbin_age = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='quantile')
kbin_fare = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='quantile')

In [123]:
trf = ColumnTransformer(transformers=[
    ('first',kbin_age,[0]),
    ('Second',kbin_fare,[1])
])

In [124]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages\sklearn\preprocessing\_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(
C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [125]:
trf.named_transformers_['first'].n_bins_

array([9])

In [126]:
trf.named_transformers_['first'].bin_edges_

array([array([ 0.42      , 16.        , 21.        , 24.        , 28.        ,
              29.69911765, 32.        , 38.        , 47.        , 80.        ])],
      dtype=object)

In [127]:
trf.named_transformers_['Second'].bin_edges_

array([array([  0.     ,   7.55   ,   7.88916,   8.05   ,  10.5    ,  14.4542 ,
               21.045  ,  26.55   ,  39.6875 ,  77.2875 , 512.3292 ])          ],
      dtype=object)

In [128]:
output = pd.DataFrame({
    'age': x_train['Age'],
    'age_trf' : x_train_trf[:,0],
    'fare': x_train['Fare'],
    'fare_trf': x_train_trf[:,1]
})

In [129]:
output

           age  age_trf      fare  fare_trf
331  45.500000      7.0   28.5000       7.0
733  23.000000      2.0   13.0000       4.0
382  32.000000      6.0    7.9250       2.0
704  26.000000      3.0    7.8542       1.0
813   6.000000      0.0   31.2750       7.0
..         ...      ...       ...       ...
106  21.000000      2.0    7.6500       1.0
270  29.699118      5.0   31.0000       7.0
860  41.000000      7.0   14.1083       4.0
435  14.000000      0.0  120.0000       9.0
102  21.000000      2.0   77.2875       9.0

[712 rows x 4 columns]

In [130]:
clf = DecisionTreeClassifier()
clf.fit(x_train_trf,y_train)
y_pred2 = clf.predict(x_test_trf)

In [131]:
accuracy_score(y_test,y_pred2)

0.6871508379888268

In [132]:
x_trf = trf.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,cv=10,scoring= 'accuracy'))

C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages\sklearn\preprocessing\_discretization.py:396: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 0 are removed. Consider decreasing the number of bins.
  warnings.warn(
C:\Users\LENOVO\AppData\Roaming\Python\Python314\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

np.float64(0.6532334581772784)

# **Binarization**

In [133]:
titanic = pd.read_csv(r"C:\Users\LENOVO\Downloads\titanic.csv",usecols=['Age','Survived','Parch','Fare','SibSp'])

In [134]:
titanic.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [135]:
titanic['family'] = titanic['SibSp'] + titanic['Parch']

In [136]:
titanic.head(3)

   Survived   Age  SibSp  Parch     Fare  family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0

In [137]:
titanic.drop(columns=['SibSp','Parch'],inplace=True)

In [138]:
titanic.head()

   Survived   Age     Fare  family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1
2         1  26.0   7.9250       0
3         1  35.0  53.1000       1
4         0  35.0   8.0500       0

In [139]:
titanic.dropna(inplace=True)

In [140]:
x = titanic.iloc[:,1:]
y =  titanic[['Survived']]

In [141]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [142]:
# without binarization
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
accuracy_score(y_test,y_pred)

0.6363636363636364

In [143]:
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,cv=10,scoring='accuracy'))

np.float64(0.6513302034428795)

In [144]:
from sklearn.preprocessing import Binarizer

In [145]:
# applying binarization
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [146]:
x_train

      Age      Fare  family
328  31.0   20.5250       2
73   26.0   14.4542       1
253  30.0   16.1000       1
719  33.0    7.7750       0
666  25.0   13.0000       0
..    ...       ...     ...
92   46.0   61.1750       1
134  25.0   13.0000       0
337  41.0  134.5000       0
548  33.0   20.5250       2
130  33.0    7.8958       0

[571 rows x 3 columns]

In [147]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

In [150]:
pd.DataFrame(x_train_trf,columns=['family','Age','Fare'])

     family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [151]:
clf1 = DecisionTreeClassifier()
clf.fit(x_train_trf,y_train)
y_pred2 = clf.predict(x_test_trf)
accuracy_score(y_test,y_pred2)

0.6293706293706294

In [153]:
x_trf = trf.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(),x_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6276017214397496)