## **Handling Date And Time**

In [25]:
import pandas as pd
import numpy as np

In [26]:
data = pd.read_csv(r"C:\Users\LENOVO\Downloads\aapl_stock_data.csv",usecols=['Date'])

In [27]:
data.head()

         Date
0  2010-01-04
1  2010-01-05
2  2010-01-06
3  2010-01-07
4  2010-01-08

In [28]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4102 entries, 0 to 4101
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4102 non-null   str
dtypes: str(1)
memory usage: 72.2 KB

In [29]:
data['Date'] = pd.to_datetime(data['Date'])

In [30]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4102 entries, 0 to 4101
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4102 non-null   datetime64[us]
dtypes: datetime64[us](1)
memory usage: 32.2 KB

## **Extract Year**

In [31]:
data['year'] = data['Date'].dt.year
data.head(3)

        Date  year
0 2010-01-04  2010
1 2010-01-05  2010
2 2010-01-06  2010

## **Extract Month**

In [32]:
data['month_no'] = data['Date'].dt.month
data.sample(3)

           Date  year  month_no
1731 2016-11-16  2016        11
3310 2023-02-28  2023         2
3032 2022-01-19  2022         1

In [33]:
data['month_name'] = data['Date'].dt.month_name()
data.sample(3)

           Date  year  month_no month_name
113  2010-06-16  2010         6       June
1280 2015-02-04  2015         2   February
248  2010-12-28  2010        12   December

In [34]:
data['Day'] = data['Date'].dt.day
data.sample(3)

           Date  year  month_no month_name  Day
1382 2015-07-01  2015         7       July    1
1771 2017-01-17  2017         1    January   17
3128 2022-06-07  2022         6       June    7

In [39]:
# day of week
data['DOW'] = data['Date'].dt.day_of_week
data.sample(3)

           Date  year  month_no month_name  Day  DOW
688  2012-09-25  2012         9  September   25    1
754  2013-01-02  2013         1    January    2    2
3924 2025-08-11  2025         8     August   11    0

In [40]:
data['Day_name'] = data['Date'].dt.day_name()
data.sample(3)

           Date  year  month_no month_name  Day  DOW  Day_name
3513 2023-12-18  2023        12   December   18    0    Monday
932  2013-09-17  2013         9  September   17    1   Tuesday
1880 2017-06-22  2017         6       June   22    3  Thursday

In [65]:
# is weekend ?
data['is_weekend'] = np.where(data['Day_name'].isin(['Sunday','Saturday','Friday']),1,0)
data['is_weekend'].value_counts()

is_weekend
0    3278
1     824
Name: count, dtype: int64

In [72]:
# extract week of the year
data['Week'] = data['Date'].dt.weekday
data.head()

        Date  year  month_no month_name  Day  DOW   Day_name  is_weekend  Week
0 2010-01-04  2010         1    January    4    0     Monday           0     0
1 2010-01-05  2010         1    January    5    1    Tuesday           0     1
2 2010-01-06  2010         1    January    6    2  Wednesday           0     2
3 2010-01-07  2010         1    January    7    3   Thursday           0     3
4 2010-01-08  2010         1    January    8    4     Friday           1     4

In [ ]:
# quarter
data['quater'] = data['Date'].dt.quarter
data.sample(3)

,Date,year,month_no,month_name,Day,DOW,Day_name,is_weekend,Week,quater
910,2013-08-15,2013,8,August,15,3,Thursday,0,3,3
2542,2020-02-10,2020,2,February,10,0,Monday,0,0,1
576,2012-04-17,2012,4,April,17,1,Tuesday,0,1,2

In [74]:
# semester
data['semester'] = np.where(data['quater'].isin([1,2]),1,2)
data.sample(3)

,Date,year,month_no,month_name,Day,DOW,Day_name,is_weekend,Week,quater,semester
2484,2019-11-14,2019,11,November,14,3,Thursday,0,3,4,2
2724,2020-10-28,2020,10,October,28,2,Wednesday,0,2,4,2
4028,2026-01-08,2026,1,January,8,3,Thursday,0,3,1,1

In [76]:
# time elapsed between dates
import datetime
today= datetime.datetime.today()
(today - data['Date']).dt.days

0       6096
1       6095
2       6094
3       6093
4       6092
        ...
4097     146
4098     145
4099     144
4100     143
4101     142
Name: Date, Length: 4102, dtype: int64

In [79]:
time = pd.read_csv(r"C:\Users\LENOVO\Downloads\archive\Youtube-Spam-Dataset.csv",usecols=['DATE'])

In [80]:
time.head()

                  DATE
0  2013-11-07T06:20:48
1  2013-11-07T12:37:15
2  2013-11-08T17:34:21
3  2013-11-09T08:28:43
4  2013-11-10T16:05:38

In [83]:
time['DATE']=pd.to_datetime(time['DATE'],errors='coerce')

In [84]:
time.head()

                 DATE
0 2013-11-07 06:20:48
1 2013-11-07 12:37:15
2 2013-11-08 17:34:21
3 2013-11-09 08:28:43
4 2013-11-10 16:05:38

In [88]:
time['Hour'] = time['DATE'].dt.hour
time['Minutes'] = time['DATE'].dt.minute
time['Seconds'] = time['DATE'].dt.second
time['time'] = time['DATE'].dt.time
time['Compleate_date'] = time['DATE'].dt.date
time.head()

                 DATE  Hour  Minutes  Seconds      time Compleate_date
0 2013-11-07 06:20:48   6.0     20.0     48.0  06:20:48     2013-11-07
1 2013-11-07 12:37:15  12.0     37.0     15.0  12:37:15     2013-11-07
2 2013-11-08 17:34:21  17.0     34.0     21.0  17:34:21     2013-11-08
3 2013-11-09 08:28:43   8.0     28.0     43.0  08:28:43     2013-11-09
4 2013-11-10 16:05:38  16.0      5.0     38.0  16:05:38     2013-11-10